language: php
php:
  - '5.6'
  - '7.0'
  
#sudo: false

branches:
  only:
    - master
    - jelix-1.7.x

addons:
    hosts:
        - testapp.local
        - testapp20.local

cache:
    directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true

services:
   - memcached
   - redis-server
   - mysql
   - postgresql

before_install:
   - phpenv config-add testapp/travis/phpconf.ini
   - phpenv config-rm xdebug.ini
   - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
   - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   - sudo ./testapp/travis/before_install.sh
   - ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update

install:
   - ./testapp/travis/install.sh

before_script:
   - ./testapp/travis/before_script.sh

script:
   - ./testapp/travis/script.sh

#after_success:
    
#after_failure:

#before_deploy:

#deploy:
#    skip_cleanup: true


#after_deploy:
    
#after_script:


