language: php
php:
  - 5.6
  
#sudo: false

branches:
  only:
    - master

addons:
    hosts:
        - testapp.local
        - testapp20.local

#cache:
#    directories:

matrix:
    fast_finish: true

services:
   - memcached
   - redis-server
   - mysql
   - postgresql

before_install:
   - sudo ./testapp/travis/before_install.sh
   - phpenv config-add testapp/travis/phpconf.ini

install:
   - ./testapp/travis/install.sh

before_script:
   - ./testapp/travis/before_script.sh

script:
   - ./testapp/travis/script.sh

#after_success:
    
#after_failure:

#before_deploy:

#deploy:
#    skip_cleanup: true


#after_deploy:
    
#after_script:


